project_id = "zvnxlsnsfjgfswtnlbgo"

[functions.send-verification-code]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.delete-user-by-email]
verify_jwt = false

[functions.approve-business-upgrade]
verify_jwt = false

[functions.request-business-upgrade]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.send-password-reset-code]
verify_jwt = false