project_id = "zvnxlsnsfjgfswtnlbgo"

[functions.send-verification-code]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.approve-business-upgrade]
verify_jwt = false

[functions.request-business-upgrade]
verify_jwt = false